# -*- coding: utf-8 -*-
# adapted from https://www.youtube.com/watch?v=uls-WmxRiTw  @https://github.com/AtsushiSakai 

# Form implementation generated from reading ui file 'path_tracking_simulator.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(521, 560)
        self.map_graphicsView = QtWidgets.QGraphicsView(Form)
        self.map_graphicsView.setGeometry(QtCore.QRect(10, 10, 500, 500))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.map_graphicsView.sizePolicy().hasHeightForWidth())
        self.map_graphicsView.setSizePolicy(sizePolicy)
        self.map_graphicsView.setMinimumSize(QtCore.QSize(500, 500))
        self.map_graphicsView.setBaseSize(QtCore.QSize(500, 500))
        self.map_graphicsView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.map_graphicsView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.map_graphicsView.setSceneRect(QtCore.QRectF(0.0, 0.0, 500.0, 500.0))
        self.map_graphicsView.setObjectName("map_graphicsView")
        self.update_path_image_pushButton = QtWidgets.QPushButton(Form)
        self.update_path_image_pushButton.setGeometry(QtCore.QRect(10, 520, 141, 30))
        self.update_path_image_pushButton.setObjectName("update_path_image_pushButton")
        self.publish_path_pushButton = QtWidgets.QPushButton(Form)
        self.publish_path_pushButton.setGeometry(QtCore.QRect(160, 520, 101, 30))
        self.publish_path_pushButton.setObjectName("publish_path_pushButton")

        self.retranslateUi(Form)
        self.update_path_image_pushButton.clicked.connect(Form.update_path_image) # type: ignore
        self.publish_path_pushButton.clicked.connect(Form.publish_path) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Path Tracking Simulator"))
        self.update_path_image_pushButton.setText(_translate("Form", "Update Path Image"))
        self.publish_path_pushButton.setText(_translate("Form", "Publish Path"))
