# -*- coding: utf-8 -*-
# adapted from https://www.youtube.com/watch?v=uls-WmxRiTw  @https://github.com/AtsushiSakai 

# Form implementation generated from reading ui file 'path_tracking_simulator.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1040, 560)
        self.map_graphicsView = QtWidgets.QGraphicsView(Form)
        self.map_graphicsView.setGeometry(QtCore.QRect(10, 10, 500, 500))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.map_graphicsView.sizePolicy().hasHeightForWidth())

        # screen 1: robot localization map -- main interface
        self.map_graphicsView.setSizePolicy(sizePolicy)
        self.map_graphicsView.setMinimumSize(QtCore.QSize(500, 500))
        self.map_graphicsView.setBaseSize(QtCore.QSize(500, 500))
        self.map_graphicsView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.map_graphicsView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.map_graphicsView.setSceneRect(QtCore.QRectF(0.0, 0.0, 500.0, 500.0))
        self.map_graphicsView.setObjectName("map_graphicsView")
        self.publish_path_pushButton = QtWidgets.QPushButton(Form)
        self.publish_path_pushButton.setGeometry(QtCore.QRect(160, 520, 101, 30))
        self.publish_path_pushButton.setObjectName("publish_path_pushButton")

        # screen 2: lidar point cloud map
        self.map_lidarView = QtWidgets.QGraphicsView(Form)
        self.map_lidarView.setGeometry(QtCore.QRect(530, 10, 500, 500))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.map_lidarView.sizePolicy().hasHeightForWidth())

        # Configure the map_lidarView widget
        self.map_lidarView.setSizePolicy(sizePolicy)
        self.map_lidarView.setMinimumSize(QtCore.QSize(500, 500))
        self.map_lidarView.setBaseSize(QtCore.QSize(500, 500))
        self.map_lidarView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.map_lidarView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.map_lidarView.setSceneRect(QtCore.QRectF(0.0, 0.0, 500.0, 500.0))
        self.map_lidarView.setObjectName("map_lidarView")
        
        # draw path button
        self.draw_path_pushButton = QtWidgets.QPushButton(Form)
        self.draw_path_pushButton.setGeometry(QtCore.QRect(270, 520, 101, 30))
        self.draw_path_pushButton.setObjectName("draw_path_pushButton")
        
        # draw obstacle button
        self.draw_obstacle_pushButton = QtWidgets.QPushButton(Form)
        self.draw_obstacle_pushButton.setGeometry(QtCore.QRect(380, 520, 111, 30))
        self.draw_obstacle_pushButton.setObjectName("draw_obstacle_pushButton")
        self.clear_obstacles_pushButton = QtWidgets.QPushButton(Form)
        self.clear_obstacles_pushButton.setGeometry(QtCore.QRect(10, 520, 141, 30))
        self.clear_obstacles_pushButton.setObjectName("clear_obstacles_pushButton")

        # create map button
        self.create_map_pushButton = QtWidgets.QPushButton(Form)
        self.create_map_pushButton.setGeometry(QtCore.QRect(500, 520, 111, 30))
        self.create_map_pushButton.setObjectName("create_map_pushButton")

        self.retranslateUi(Form)
        self.publish_path_pushButton.clicked.connect(Form.publish_path) # type: ignore
        self.draw_path_pushButton.clicked.connect(Form.enable_draw_path) # type: ignore
        self.draw_obstacle_pushButton.clicked.connect(Form.enable_draw_obstacle) # type: ignore
        self.clear_obstacles_pushButton.clicked.connect(Form.clear_obstacles) # type: ignore
        self.create_map_pushButton.clicked.connect(Form.create_map) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Path Tracking Simulator"))
        self.publish_path_pushButton.setText(_translate("Form", "Publish Path"))
        self.draw_path_pushButton.setText(_translate("Form", "Draw Path"))
        self.draw_obstacle_pushButton.setText(_translate("Form", "Draw Obstacle"))
        self.clear_obstacles_pushButton.setText(_translate("Form", "Clear Obstacles"))
        self.create_map_pushButton.setText(_translate("Form", "Create Map"))
